### ISSUE TITLE
Sound needs to be reimplemented

### ISSUE THREAD

**Issue by cuckydev** [cuckydev/CuckyDOOM#2]
I'm not even gonna try messing around with the old ass sound server, I'll need to write one myself in software using SDL2

**Comment by Clownacy** [comment]
I'm not the most familiar with Linux Doom's sound code, but I did look into its mixer while working on clownaudio. From what I could tell, it was pretty modular, and projects like PrBoom have successfully plugged it into the main engine, allowing it to be used as-is. Of course, PrBoom did make some improvements like increasing the sound limit, but still. It's not necessary to completely rewrite it.

**Comment by cuckydev** [comment]
sound has been (partially) implemented as of https://github.com/cuckydev/CuckyDOOM/commit/2e534384cf9fbd02174ebaf8c7c3fa1d26e54972
